openapi: 3.0.0
info:
  title: TDX Airport Information Plugin
  description: 查詢特定台灣機場的詳細資訊
  version: 1.0.0
  contact:
    name: Developer
    email: your-email@example.com

# API 授權方式
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: authorization

security:
  - apiKeyAuth: []

# 定義 API 路徑
paths:
  Airport/{AirportID}:
    get:
      summary: 查詢特定機場的詳細資訊
      description: 根據機場代碼查詢機場的資訊
      operationId: getAirportByID
      parameters:
        - name: AirportID
          in: path
          required: true
          description: 機場的三字代碼，例如 TPE、TSA
          schema:
            type: string
      responses:
        '200':
          description: 成功返回機場資料
          content:
            application/json:
              schema:
                type: object
                properties:
                  AirportID:
                    type: string
                    description: 機場的代碼
                  AirportName:
                    type: object
                    properties:
                      Zh_tw:
                        type: string
                        description: 機場的中文名稱
                      En:
                        type: string
                        description: 機場的英文名稱
                  CityName:
                    type: object
                    properties:
                      Zh_tw:
                        type: string
                        description: 城市的中文名稱
                      En:
                        type: string
                        description: 城市的英文名稱
                  Location:
                    type: object
                    properties:
                      Latitude:
                        type: number
                        format: float
                        description: 機場的緯度
                      Longitude:
                        type: number
                        format: float
                        description: 機場的經度
                  IATA:
                    type: string
                    description: IATA 代碼
                  ICAO:
                    type: string
                    description: ICAO 代碼
        '401':
          description: 未授權
        '404':
          description: 找不到指定的機場
        '500':
          description: 伺服器錯誤
# 定義 API 路徑
paths:
  Airline/{AirlineID}:
    get:
      summary: 查詢特定航空公司的詳細資訊
      description: 根據航空公司代碼查詢航空公司的資訊
      operationId: getAirlineByID
      parameters:
        - name: AirlineID
          in: path
          required: true
          description: 航空公司的代碼，例如 CI (中華航空)、BR (長榮航空)
          schema:
            type: string
      responses:
        '200':
          description: 成功返回航空公司資料
          content:
            application/json:
              schema:
                type: object
                properties:
                  AirlineID:
                    type: string
                    description: 航空公司的代碼
                  AirlineName:
                    type: object
                    properties:
                      Zh_tw:
                        type: string
                        description: 航空公司的中文名稱
                      En:
                        type: string
                        description: 航空公司的英文名稱
                  Country:
                    type: object
                    properties:
                      Zh_tw:
                        type: string
                        description: 所屬國家的中文名稱
                      En:
                        type: string
                        description: 所屬國家的英文名稱
                  IATA:
                    type: string
                    description: IATA 代碼
                  ICAO:
                    type: string
                    description: ICAO 代碼
        '401':
          description: 未授權
        '404':
          description: 找不到指定的航空公司
        '500':
          description: 伺服器錯誤
# 定義 API 路徑
paths:
  /v2/Air/GeneralSchedule/International:
    get:
      summary: 取得國際航空定期時刻表
      description: 查詢所有國際航班的定期時刻表
      operationId: getInternationalFlightSchedule
      parameters:
        - name: DepartureAirportID
          in: query
          required: true
          description: 出發機場的代碼 (例如 TPE)
          schema:
            type: string
        - name: ArrivalAirportID
          in: query
          required: true
          description: 到達機場的代碼 (例如 JFK)
          schema:
            type: string
        - name: airlineIATA
          in: query
          required: false
          description: 航空公司的 IATA 代碼 (例如 CI)
          schema:
            type: string
        - name: startDate
          in: query
          required: false
          description: 查詢航班的開始日期 (ISO8601 格式，例如 2024-09-12)
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: false
          description: 查詢航班的結束日期 (ISO8601 格式，例如 2024-09-12)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: 成功返回國際航班定期時刻表
          content:
            application/json:
              schema:
                type: object
                properties:
                  airline:
                    type: object
                    properties:
                      IATA:
                        type: string
                        description: 航空公司的 IATA 代碼
                      name:
                        type: string
                        description: 航空公司名稱
                  flights:
                    type: array
                    items:
                      type: object
                      properties:
                        flightNumber:
                          type: string
                          description: 航班號碼
                        departureTime:
                          type: string
                          format: date-time
                          description: 出發時間 (ISO8601 格式)
                        arrivalTime:
                          type: string
                          format: date-time
                          description: 到達時間 (ISO8601 格式)
                        departureAirport:
                          type: string
                          description: 出發機場的代碼
                        arrivalAirport:
                          type: string
                          description: 到達機場的代碼
                        airlineIATA:
                          type: string
                          description: 航空公司的 IATA 代碼
        '401':
          description: 未授權
        '404':
          description: 找不到符合條件的航班資料
        '500':
          description: 伺服器錯誤
# 伺服器端點
servers: 
  - url: https://tdx.transportdata.tw/api/basic/v2/Air/
    description: TDX 特定機場資訊 API 伺服器
