openapi: 3.0.0
info:
  title: TDX Airport Information Plugin
  description: 查詢特定機場的詳細資訊
  version: 1.0.0
servers:
  - url: http://211.20.7.116:8839/api/v1

paths:
  /airplane/airport:
    post:
      summary: Retrieve airport information
      operationId: getAirportInfo
      requestBody:
        description: Airport ID request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirportRequest'
      responses:
        '200':
          description: 成功返回機場資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirportResponse'
        '400':
          description: 無效的請求
        '404':
          description: 找不到機場

components:
  schemas:
    AirportRequest:
      type: object
      properties:
        AirportID:
          type: string
          description: 要查詢的機場 ID
          example: TPE

    AirportResponse:
      type: object
      properties:
        AirportID:
          type: string
          description: 機場代碼
          example: TPE
        AirportName:
          type: object
          properties:
            Zh_tw:
              type: string
              description: 機場的中文名稱
              example: 桃園國際機場
            En:
              type: string
              description: 機場的英文名稱
              example: Taoyuan International Airport
        AirportIATA:
          type: string
          description: 機場的 IATA 代碼
          example: TPE
        AirportICAO:
          type: string
          description: 機場的 ICAO 代碼
          example: RCTP
        AirportPosition:
          type: object
          properties:
            PositionLon:
              type: number
              format: float
              description: 經度
              example: 121.231976
            PositionLat:
              type: number
              format: float
              description: 緯度
              example: 25.0770119995
            GeoHash:
              type: string
              description: 機場位置的 GeoHash
              example: wsqnwtnkj
        AirportCityName:
          type: object
          nullable: true
          description: 城市名稱（可能為空）
          properties:
            Zh_tw:
              type: string
              description: 城市的中文名稱
              example: 桃園市
            En:
              type: string
              description: 城市的英文名稱
              example: Taoyuan
        AirportAddress:
          type: string
          description: 機場地址
          example: 桃園市大園區航站南路9號
        AirportPhone:
          type: string
          description: 機場電話號碼
          example: 03-2735081
        AirportNationality:
          type: string
          description: 機場的國籍
          example: TW
        AuthorityID:
          type: string
          description: 機場管理機構的 ID
          example: CAA
        UpdateTime:
          type: string
          format: date-time
          description: 機場資訊的更新時間
          example: 2024-09-17T08:43:40+08:00
        VersionID:
          type: integer
          description: 資訊的版本 ID
          example: 1484

# # 定義 API 路徑
# paths:
#   Airline/{AirlineID}:
#     get:
#       summary: 查詢特定航空公司的詳細資訊
#       description: 根據航空公司代碼查詢航空公司的資訊
#       operationId: getAirlineByID
#       parameters:
#         - name: AirlineID
#           in: path
#           required: true
#           description: 航空公司的代碼，例如 CI (中華航空)、BR (長榮航空)
#           schema:
#             type: string
#       responses:
#         '200':
#           description: 成功返回航空公司資料
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   AirlineID:
#                     type: string
#                     description: 航空公司的代碼
#                   AirlineName:
#                     type: object
#                     properties:
#                       Zh_tw:
#                         type: string
#                         description: 航空公司的中文名稱
#                       En:
#                         type: string
#                         description: 航空公司的英文名稱
#                   Country:
#                     type: object
#                     properties:
#                       Zh_tw:
#                         type: string
#                         description: 所屬國家的中文名稱
#                       En:
#                         type: string
#                         description: 所屬國家的英文名稱
#                   IATA:
#                     type: string
#                     description: IATA 代碼
#                   ICAO:
#                     type: string
#                     description: ICAO 代碼
#         '401':
#           description: 未授權
#         '404':
#           description: 找不到指定的航空公司
#         '500':
#           description: 伺服器錯誤
# # 定義 API 路徑
# paths:
#   GeneralSchedule/International:
#     get:
#       summary: 取得國際航空定期時刻表
#       description: 查詢所有國際航班的定期時刻表，並可過濾返回的航班資料。
#       operationId: getInternationalFlightSchedule
#       parameters:
#         - name: DepartureAirportID
#           in: query
#           required: true
#           description: 出發機場的代碼 (例如 TPE)
#           schema:
#             type: string
#         - name: ArrivalAirportID
#           in: query
#           required: true
#           description: 到達機場的代碼 (例如 JFK)
#           schema:
#             type: string
#         - name: airlineIATA
#           in: query
#           required: false
#           description: 航空公司的 IATA 代碼 (例如 CI)
#           schema:
#             type: string
#         - name: ScheduleStartDate
#           in: query
#           required: false
#           description: 查詢航班的開始日期 (ISO8601 格式，例如 2024-09-12)
#           schema:
#             type: string
#             format: date
#         - name: endDate
#           in: query
#           required: false
#           description: 查詢航班的結束日期 (ISO8601 格式，例如 2024-09-12)
#           schema:
#             type: string
#             format: date
#         - name: top
#           in: query
#           required: false
#           description: 限制返回的航班數量
#           schema:
#             type: integer
#             example: 10
#       responses:
#         '200':
#           description: 成功返回國際航班定期時刻表
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   airline:
#                     type: object
#                     properties:
#                       IATA:
#                         type: string
#                         description: 航空公司的 IATA 代碼
#                       name:
#                         type: string
#                         description: 航空公司名稱
#                   flights:
#                     type: array
#                     items:
#                       type: object
#                       properties:
#                         flightNumber:
#                           type: string
#                           description: 航班號碼
#                         departureTime:
#                           type: string
#                           format: date-time
#                           description: 出發時間 (ISO8601 格式)
#                         departureAirport:
#                           type: string
#                           description: 出發機場的代碼
#                         arrivalAirport:
#                           type: string
#                           description: 到達機場的代碼
#                         airlineIATA:
#                           type: string
#                           description: 航空公司的 IATA 代碼
#         '401':
#           description: 未授權
#         '404':
#           description: 找不到符合條件的航班資料
#         '500':
#           description: 伺服器錯誤
