openapi: 3.0.0
info:
  title: TDX Airport Information Plugin
  description: 查詢有關航空的詳細資訊
  version: 1.0.0
servers:
  - url: https://davinci-airplane.nutc-imac.com/api/v1

# paths:
#   /airplane/airport:
#     post:
#       summary: 查詢有關機場的資訊
#       operationId: getAirportInfo
#       requestBody:
#         description: Airport ID request
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: '#/components/schemas/AirportRequest'
#       responses:
#         '200':
#           description: 成功返回機場資訊
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/AirportResponse'
#         '400':
#           description: 無效的請求，請檢查 AirportID 或輸入格式
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Error'
#         '404':
#           description: 找不到機場
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Error'
#         '500':
#           description: 伺服器內部錯誤
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/Error'

#   /airplane/airline:
#     post:
#       summary: 查詢有功航空公司的資訊
#       operationId: getAirlineInfo
#       requestBody:
#         description: Airline ID request
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: '#/components/schemas/AirlineRequest'
#       responses:
#         '200':
#           description: 成功返回航空公司資料
#           content:
#             application/json:
#               schema:
#                 $ref: '#/components/schemas/AirlineResponse'
#         '401':
#           description: 未授權
#         '404':
#           description: 找不到指定的航空公司
#         '500':
#           description: 伺服器錯誤

#   /airplane/flight:
#     post:
#       summary: 查詢航班資訊
#       operationId: getFlightInfo
#       requestBody:
#         description: 航班查詢請求
#         required: true
#         content:
#           application/json:
#             schema:
#               $ref: '#/components/schemas/FlightRequest'
#       responses:
#         '200':
#           description: 成功返回航班資料
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   $ref: '#/components/schemas/FlightResponse'
#         '400':
#           description: 無效的請求
#         '404':
#           description: 找不到航班資料


/airplane/test:
    post:
      summary: 獲取航班資訊
      operationId: getTestData
      responses:
        '200':
          description: 成功返回測試數據
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestResponse'

components:
  schemas:
    TestResponse:
      type: object
      properties:
        AirportID:
          type: string
          description: 機場代碼
          example: TPE
        AirportName:
          type: object
          properties:
            Zh_tw:
              type: string
              description: 機場的中文名稱
              example: 桃園國際機場
            En:
              type: string
              description: 機場的英文名稱
              example: Taoyuan International Airport
        AirportIATA:
          type: string
          description: 機場的 IATA 代碼
          example: TPE
        AirportICAO:
          type: string
          description: 機場的 ICAO 代碼
          example: RCTP
        AirportPosition:
          type: object
          properties:
            PositionLon:
              type: number
              format: float
              description: 經度
              example: 121.231976
            PositionLat:
              type: number
              format: float
              description: 緯度
              example: 25.0770119995
            GeoHash:
              type: string
              description: 機場位置的 GeoHash
              example: wsqnwtnkj
        AirportCityName:
          type: object
          nullable: true
          description: 城市名稱（可能為空）
          properties:
            Zh_tw:
              type: string
              description: 城市的中文名稱
              example: 桃園市
            En:
              type: string
              description: 城市的英文名稱
              example: Taoyuan
        AirportAddress:
          type: string
          description: 機場地址
          example: 桃園市大園區航站南路9號
        AirportPhone:
          type: string
          description: 機場電話號碼
          example: 03-2735081
        AirportNationality:
          type: string
          description: 機場的國籍
          example: TW
        AuthorityID:
          type: string
          description: 機場管理機構的 ID
          example: CAA
        UpdateTime:
          type: string
          format: date-time
          description: 機場資訊的更新時間
          example: 2024-09-17T08:43:40+08:00
        VersionID:
          type: integer
          description: 資訊的版本 ID
          example: 1484
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          description: 錯誤狀態碼
          example: 400
        errorMessage:
          type: string
          description: 錯誤訊息
          example: 'Invalid AirportID provided'
         
