openapi: 3.0.0
info:
  title: 氣象局氣象資料 API
  description: 這個 API 讓你可以查詢氣象資料開放平台提供的即時天氣資訊。
  version: 1.0.0
servers:
  - url: https://opendata.cwb.gov.tw/api/v1/rest/datastore
paths:
  /O-A0003-001:
    get:
      summary: 查詢即時天氣資訊
      parameters:
        - name: Authorization
          in: query
          required: true
          schema:
            type: string
          description: "CWB-29505DAD-7965-40EE-83B4-962CC736EDAD"
        - name: locationName
          in: query
          required: false
          schema:
            type: string
          description: "指定要查詢的地區名稱"
      responses:
        '200':
          description: 成功回應
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      location:
                        type: array
                        items:
                          type: object
                          properties:
                            locationName:
                              type: string
                            weatherElement:
                              type: array
                              items:
                                type: object
                                properties:
                                  elementName:
                                    type: string
                                  elementValue:
                                    type: string
