openapi: 3.0.0
info:
  title: Nominatim Address API
  description: 使用經緯度來反查地址
  version: 1.0.0
servers:
  - url: https://nominatim.openstreetmap.org
paths:
  /reverse:
    get:
      summary: 獲取地址信息
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
          description: 緯度 (Latitude)
        - name: lon
          in: query
          required: true
          schema:
            type: number
          description: 經度 (Longitude)
        - name: format
          in: query
          required: true
          schema:
            type: string
            default: jsonv2
          description: 回應格式
      responses:
        '200':
          description: 成功獲取地址
          content:
            application/json:
              schema:
                type: object
                properties:
                  display_name:
                    type: string
                    description: 反查得到的地址名稱
