
openapi: 3.0.0
info:
  title: 氣象局氣象資料 API
  description: 這個 API 讓你可以查詢氣象資料開放平台提供的即時天氣資訊。
  version: 1.0.0
servers:
  - url: https://opendata.cwb.gov.tw/api/v1/rest/datastore
paths:
  /F-C0032-001:
    get:
      summary: 一般天氣預報 - 今日36小時天氣預報
      parameters:
        - name: Authorization
          in: query
          required: true
          schema:
            type: string
          description:  直接填入這個 API KEY:"CWB-29505DAD-7965-40EE-83B4-962CC736EDAD"
        - name: locationName
          in: query
          required: true
          schema:
            type: string
            enum:
              - %E5%8F%B0%E5%8C%97%E5%B8%82  # 台北市
              - %E8%87%BA%E4%B8%AD%E5%B8%82  # 台中市
              - %E9%AB%98%E9%9B%84%E5%B8%82  # 高雄市
              - %E6%96%B0%E7%AB%B9%E5%B8%82  # 新竹市
            description: 選擇你要查詢的地區名稱，使用 URL 編碼過的值
      responses:
        '200':
          description: 成功回應
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    type: object
                    properties:
                      location:
                        type: array
                        items:
                          type: object
                          properties:
                            locationName:
                              type: string
                            weatherElement:
                              type: array
                              items:
                                type: object
                                properties:
                                  elementName:
                                    type: string
                                  elementValue:
                                    type: string
